language: java
sudo: false # faster builds

script:
  - mvn package -Dmaven.javadoc.skip=true -V -B

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

notifications:
  webhooks: http://internal.craftmania.cz/travis-ci.php