# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# ProxyJoin Bungee
# Pouze hraci s touto IP se budou moct pripojit
proxy-ips:
 - '0.0.0.1'

# Povolene IP, ktere se mohou pripojit mimo BungeeCord
disable-ips:
 - '0.0.0.1'

# ID serveru pro statistiky
server: Survival

# Oznamovani do chatu o hlasech
reminder: true

# Hlasovani
hlasovani: true

# Statistiky do SQL
stats-tracker: true

# Update tablist task
tablist-update: false

# Zakazani podobnych nicku MrWakeCZ & mrwakecz (UUID bug)
economyfix: false

# Prometheus statistiky
prometheus:
 state: false
 port: 9225

# Materialy pro DurabilityWarner
# Funkce pro VIP
materials:
  - 'IRON_SPADE'
  - 'IRON_AXE'
  - 'IRON_PICKAXE'
  - 'IRON_SWORD'
  - 'DIAMOND_SPADE'
  - 'DIAMOND_AXE'
  - 'DIAMOND_SWORD'
  - 'DIAMOND_PICKAXE'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'FLINT_AND_STEEL'
  - 'BOW'
  - 'SHIELD'

# Regexy pro blokovane tagy
blocked-tags:
  - \b(s+(\W|\d|_)*r+(\W|\d|_)*a+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*y+(\W|\d|_)*)
  - \b(v+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)