# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Zda-li je server pouze na testy!
testing: false

# ID serveru pro statistiky
server: Survival

# Oznamovani do chatu o hlasech
reminder: true

# Hlasovani
hlasovani: true

# Barevne psani v kovadline
coloredanvils: false

# Prometheus statistiky
prometheus:
 state: false
 port: 9225

# Detekce prikazu psanych AT
ats-commands:
  enabled: true
  ignored-commands:
   - /msg

# Nastaveni oznacovani
mentions:
  prefix: "@"