# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Zda-li je server pouze na testy!
testing: false

# ID serveru pro statistiky
server: Survival

# Nastaveni slotu na danem serveru
totalSlots: 40
reservedSlots: 5

# Oznamovani do chatu o hlasech
reminder: true

# Barevne psani v kovadline
coloredanvils: false

# Integrace a zasílání exceptions na Sentry
sentry-dsn: ''

# Nastaveni oznacovani
mentions:
  prefix: "@"

# Ochrana na drop kosmetických itemů
protect-drop-cosmetic:
 - NETHERITE_SWORD
 - NETHERITE_SHOVEL
 - NETHERITE_AXE
 - NETHERITE_PICKAXE
 - NETHERITE_HOE
 - SUGAR