# Database
host: 127.0.0.1
port: 3306
database: dbName
user: root
password: password

# Detekce OP itemu
detection: false

# ProxyJoin Bungee
# Pouze hraci s touto IP se budou moct pripojit
proxy-ips:
 - '0.0.0.1'

# Povolene IP, ktere se mohou pripojit mimo BungeeCord
disable-ips:
 - '0.0.0.1'

# ID serveru pro statistiky
server: Survival

# Oznamovani do chatu o hlasech
reminder: true

# Hlasovani
hlasovani: true

# Statistiky do SQL
stats-tracker: true

# Update tablist task
tablist-update: false