#
# CRAFTMANAGER MAIN CONFIG
#

# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# Test mod
# Pokud je test mod povolený, nebudou fungovat veškeré synchronizace na serveru.
testing: false

# ID serveru dle kterého bude plugin fungovat
# Povolené hodnoty: skyblock, survival, prison, creative, vanilla atd.
server: Survival

# Nastavení server slotů, ovšem ne vždy funguje správně.
totalSlots: 40
reservedSlots: 5

# Aktivace barevního psaní v kovadlině
# Tato funkce plně handluje i výsledky v kovadlině, může tedy rozbít i kovadlinu
# jelikož od 1.16 to lze udělat jinak.
coloredanvils: false

# Sentry odkaz na zasílání chyb skrz CraftLibs
sentry-dsn: ''

# Ochrana na drop kosmetických itemů
protect-drop-cosmetic:
 - NETHERITE_SWORD
 - NETHERITE_SHOVEL
 - NETHERITE_AXE
 - NETHERITE_PICKAXE
 - NETHERITE_HOE
 - NETHERITE_HELMET
 - NETHERITE_CHESTPLATE
 - NETHERITE_LEGGINGS
 - NETHERITE_BOOTS
 - LEATHER_HELMET
 - LEATHER_CHESTPLATE
 - LEATHER_LEGGINGS
 - LEATHER_BOOTS
 - DIAMOND_SWORD
 - SUGAR