# Napojeni na SQL
sql:
 hostname: host
 port: 3306
 database: database
 username: user
 password: password

# Nastaveni SQL
settings:
 minimumConnections: 2
 maximumConnections: 5
 timeout: 30000

# ProxyJoin Bungee
# Pouze hraci s touto IP se budou moct pripojit
proxy-ips:
 - '0.0.0.1'

# Povolene IP, ktere se mohou pripojit mimo BungeeCord
disable-ips:
 - '0.0.0.1'

# Zda-li je server pouze na testy!
testing: false

# ID serveru pro statistiky
server: Survival

# Oznamovani do chatu o hlasech
reminder: true

# Hlasovani
hlasovani: true

# Statistiky do SQL
stats-tracker: true

# Update tablist task
tablist-update: false

# Barevne psani v kovadline
coloredanvils: false

# Zakazani podobnych nicku MrWakeCZ & mrwakecz (UUID bug)
economyfix: false

# Detekce prikazu psanych AT
ats-commands:
  enabled: true
  ignored-commands:
   - /msg

# Nastaveni oznacovani
mentions:
  prefix: "@"


# Materialy pro DurabilityWarner
# Funkce pro VIP
materials:
  - 'IRON_SPADE'
  - 'IRON_AXE'
  - 'IRON_PICKAXE'
  - 'IRON_SWORD'
  - 'DIAMOND_SPADE'
  - 'DIAMOND_AXE'
  - 'DIAMOND_SWORD'
  - 'DIAMOND_PICKAXE'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'FLINT_AND_STEEL'
  - 'BOW'
  - 'SHIELD'

# Regexy pro blokovane tagy
blocked-tags:
  - \b(s+(\W|\d|_)*r+(\W|\d|_)*a+(\W|\d|_)*c+(\W|\d|_)*k+(\W|\d|_)*)
  - \b(v+(\W|\d|_)*o+(\W|\d|_)*l+(\W|\d|_)*e+(\W|\d|_)*)

# Death messages
# Vsetky messages davej do stringlistu!
d_msgs:
  enabled: true
  cactus:
   - "§fHrac %player% byl upichan k smrti."
   - "§fHrac %player% skocil na kaktus."
  drown:
   - "§f%player% se utopil."
  creeper:
   - "§f%player% zacal hazet rukama do vsech smeru."
  player:
   - "§f%player% byl zabit hracem %attacker%."
  player_weapon:
   - "§f%player% byl zabit hracem %attacker% pomoci %weapon%."
  mob:
   - "§f%player% byl zabit mobem %mob%."
  fall:
   - "§f%player% si zlomil sve nozicky."
  falling_block:
    - "§f%player% byl rozplesknut kovadlinou jak palacinka."
  fire: # + fire_tick + hot_floor
   - "§f%player% uhorel."
  lava:
   - "§f%player% byl roztopen jak cokolada."
  lightning:
   - "§f%player% byl zasazen bleskem."
  magic:
   - "§f%player% si hral na harryho pottera."
  projectile:
   - "§f%player% byl zastrelen."
  suffocation:
   - "§f%player% se udusil v blocku."
  thorns:
   - "§f%player% zapomnel na enchant thorns."
  void:
   - "§f%player% spadl do prazdnoty vsech kwaku."
  wither:
   - "§f%player% se uwitheroval."
  dragon_breath:
    - "§f%player% byl usmazen dracim dechem."
  tnt:
    - "§f%player% byl odpalen na severni pol."
  starvation:
    - "§f%player% vyhladovel."
  unknown:
    - "§f%player% umrel, protoze kwak roztrhl kabel."