name: CraftManager
main: cz.wake.manager.Main
authors: [MrWakeCZ]
version: 1.1.0

commands:
    menu:
      description: Zakladni prikaz
    coinshop:
      description: Prikaz na otevreni coinshopu
    particles:
      description: Prikaz na otevreni particles menu
      aliases: [part]
    coins:
      description: Prikaz na zjisteni craftcoinu
    cc:
      description: Prikaz pro zjisteni craftcoinu
    glow:
      description: Prikaz pro VIP
    fakevote:
      description: Fakevote
    chatcolor:
      description: Zmena barvy
    help:
      description: Help pro servery
    survival:
      description: Server teleport
    skyblock:
      description: Server teleport
    creative:
      description: Server teleport
    creative2:
      description: Server teleport
    prison:
      description: Server teleport
    vanilla:
      description: Server teleport
    factions:
      description: Server teleport
    bedwars:
      description: Server teleport
    skywars:
      description: Server teleport
    arcade:
      description: Server teleport
    skygiants:
      description: Server teleport
    vanillasb:
      description: Server teleport
    disenchant:
      description: Prikaz pro VIP
    vote:
      description: Prikaz na zobrazeni odkazu k hlasovani