name: CraftManager
main: cz.wake.manager.Main
authors: [MrWakeCZ]
version: 1.0.2
depend: [SuperbVote]

commands:
    menu:
      description: Zakladni prikaz
    coinshop:
      description: Prikaz na otevreni coinshopu
    particles:
      description: Prikaz na otevreni particles menu
      aliases: [part]